# Generated by Django 3.0.8 on 2020-08-04 18:46

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('ethnicity', models.CharField(choices=[('Black or African American', 'Black'), ('White or Caucasian', 'White or Caucasian'), ('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Multiracial', 'Multiracial'), ('Other', 'Other')], max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], max_length=11)),
                ('sexual_preference', models.CharField(choices=[('Heterosexual or Straight', 'Heterosexual or Straight'), ('Bisexual', 'Bisexual'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Pansexual', 'Pansexual'), ('Asexual', 'Asexual'), ('Prefer Not to Disclose', 'Prefer Not to Disclose')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=125)),
                ('education', models.CharField(blank=True, choices=[('Less than high school degree', 'Less than high school degree'), ('High school degree or equivalent (e.g. GED)', 'High school degree or equivalent (e.g. GED)'), ('Some college but no degree', 'Some college but no degree'), ('Associate degree', 'Associate degree'), ('Bachelor degree', 'Bachelor degree'), ('Graduate degree', 'Graduate degree')], max_length=45)),
                ('disability', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
