# Generated by Django 3.0.8 on 2020-08-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200804_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(choices=[('Black or African American', 'Black'), ('White or Caucasian', 'White or Caucasian'), ('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Asian or Asian American', 'Asian or Asian American'), ('Multiracial', 'Multiracial'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Transgender', 'Transgender'), ('Other', 'Other')], max_length=11),
        ),
    ]
