# Generated by Django 3.0.8 on 2020-08-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.IntegerField()),
                ('age', models.IntegerField()),
                ('orientation', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('disability', models.IntegerField()),
                ('education', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='business',
            name='Location',
            field=models.CharField(default='Atlanta', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='Name',
            field=models.CharField(default='My Business', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='Type',
            field=models.CharField(choices=[('Healthcare', 'Healthcare'), ('Restaurants', 'Restaurants'), ('Shopping', 'Shopping'), ('Education', 'Education')], default='exit', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='finqueue.Business'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
