# Generated by Django 3.0.8 on 2020-08-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finqueue', '0002_auto_20200806_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Type',
            new_name='business_type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
